[package]
name = "bingbg"
version = "0.1.0"
authors = ["Rrogntudju"]
edition = "2018"
build = "build/build.rs"

[dependencies]
reqwest = "0.9.8"
winapi = {version = "0.3.6", features = ["winuser"] }
image = "0.21.0"
serde_json = "1.0.36"

[build-dependencies]
winres = "0.1.9"
