[package]
name = "bingbg"
version = "0.1.2"
authors = ["Rrogntudju"]
edition = "2018"
build = "build/build.rs"

[dependencies]
minreq = { version = "2", features = ["https", "json-using-serde"] }
winapi = {version = "0.3", features = ["winuser"] }
image = {version = "0.22", default-features = false, features = ["jpeg", "bmp"]}
serde_json = "1"

[build-dependencies]
winres = "0.1"

[profile.release]
lto = true 
codegen-units = 1
panic = "abort"