[package]
name = "bingbg"
version = "0.1.0"
authors = ["Rrogntudju"]
edition = "2018"
build = "build/build.rs"

[dependencies]
reqwest = "0.9"
winapi = {version = "0.3", features = ["winuser"] }
image = "0.21"
serde_json = "1"

[build-dependencies]
winres = "0.1"
